# Generated by Django 4.0.4 on 2023-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('postponed', 'Postponed'), ('late', 'Late')], default='pending', max_length=20),
        ),
    ]
